### ISSUE TITLE
add project structure vignette based on blog posts

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#1]
- [x] <http://predictiveecology.org/2018/06/14/managing-large-spades-projects.html>
- [x]  <http://predictiveecology.org/2018/08/16/working-with-modules-and-projects.html>
- [x] using relative filepaths
- [x] self-contained package libraries (`Require`)

**Comment by achubaty** [comment]
discuss using relative filepaths, and self-contained package libraries!

**Comment by achubaty** [comment]
prefer drat repo over `install_github`?

```r
## assumes devel tools installed (e.g. Rtools)
if (!require("Require")) {install.packages("Require"); library(Require)}
Require::setup("packages")
Require(c("SpaDES", "PredictiveEcology/SpaDES.experiment", "raster", "PredictiveEcology/LandR", "dplyr", "data.table", "achubaty/amc"))
```

vs.

```r
drat:::add("PredictiveEcology")

if (!require("Require")) {install.packages("Require"); library(Require)}
Require::setup("packages")
Require(c("SpaDES", "SpaDES.experiment", "raster", "LandR", "dplyr", "data.table", "amc"))
```

**Comment by eliotmcintire** [comment]
We will have to get used to `drat` ... basically, if I understand correctly, it is more like "releases"... which may be explicitly created by us, or automatically generated 1x per week, for example. So, it is generally not as "hot off the press" as `install_github`. This is likely a better solution for most people.
