### ISSUE TITLE
update Rstudio package manager urls

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#22]
with https://github.com/PredictiveEcology/Require/issues/73

update to use new posit.co urls:

e.g., `https://packagemanager.posit.co/cran/__linux__/focal/latest/src/contrib/future_1.31.0.tar.gz`

**Comment by eliotmcintire** [comment]
I don't think this affects `SpaDES.project`. It is not set here. Closing this. It is fixed in PredictiveEcology/Require#73
