### ISSUE TITLE
allow user to disable gitignore update

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#23]
currently, `setupProject()` is overwriting `.gitignore`, interfering with git submodules and `.Rprofile`. (we should revisit the decision to ignore .Rprofile)

**Comment by eliotmcintire** [comment]
It isn't supposed to be overwriting `.gitignore`. Can you describe what you are observing?  It is only modifying two lines... `packagePath` and `modulePath`, which I think is the correct behaviour. It doesn't touch anything else.

**Comment by eliotmcintire** [comment]
Perhaps a `reprex`?

**Comment by achubaty** [comment]
Neither of those should be touched, so I want to turn this off.

1. `packagePath` may not be a project subdirectory, so it doesn't make sense to add it here (it's also incorrect in this case in that it adds `4.2` to `.gitignore` and not the main package directory.

```r
pkgDir <- file.path(tools::R_user_dir(basename(prjDir), "data"), "packages",
                        version$platform, getRversion()[, 1:2])
```

2. `modulePath` may contain git submodules. Adding it to the project `.gitignore` doesn't make sense, and may prevent changes in those modules or new modules from being properly registered.

**Comment by achubaty** [comment]
can this please be merged asap? it is fully backwards compatible: the default behaviour is the same. it only changes if the user sets the option `SpaDES.project.updateGitIgnore = FALSE`.

**Comment by achubaty** [comment]
I've updated the pending PR (#25) with the latest changes on the `transition` branch, and tested. It's ready to go.

**Comment by eliotmcintire** [comment]
This PR is building a work around that is not the correct solution. I will try to make the correct solution now.

**Comment by eliotmcintire** [comment]
FYI: there are 3 use cases:

1. Users not using `git`
2. Users using git, but only for the modules (i.e., not a git repo with git submodules)
3. Users using git submodule infrastructure, where modules are themselves (possibly) git repositories.

The solution provided in this PR only deals with the 2nd and 3rd cases, as an option. This leaves it in the realm of _secret handshake_ (i.e., if you know what you need to know, then it will work), which I am trying to not use.

**Comment by achubaty** [comment]
yes, this is a quick workaround until a more throrough solution is implmented and tested. reviewing every commit made to a shared repo and restoring `.gitignore` to it's original state (because of inadvertant commits) is taking more time than it needs to when we can simply turn off this behaviour for now.

**Comment by eliotmcintire** [comment]
The `transitions` branch of `SpaDES.project` is not for work arounds. It is "a complete solution without work arounds". I have pushed something that deals with the 3 cases.

**Comment by eliotmcintire** [comment]
It is working for cases 1 and 3 above.

**Comment by achubaty** [comment]
thank you! this looks like it's working.

**Comment by eliotmcintire** [comment]
Minor tweaks for Test Case 2. Working for that too now.

**Comment by achubaty** [comment]
hmmm it's not quite there yet. .gitignore being modified again.

**Comment by eliotmcintire** [comment]
Are you sure that you are using the correct version of the package?  There
are likely 2 versions (personal and project)

**Comment by achubaty** [comment]
Yes, using latest version (only a single version, in project dir). It's not happening everytime I run things though.
