### ISSUE TITLE
`setupProject` examples have an error?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.project#37]
In using `SpaDES.project@49100296b6f4515e7f3a594ee374025ecec095d6` (presently the head of `windowsTesting`) the examples for `setupProject` seem to have an error:

![image](https://github.com/PredictiveEcology/SpaDES.project/assets/22214224/e875cebe-d212-4f87-a8c4-78a0a8b0e836)

**Comment by eliotmcintire** [comment]
Thank you, dealt with now.
