### ISSUE TITLE
`setupProject(..., sideEffects)` documentation seems circular and may ned more detail

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.project#41]
With `SpaDES.project@windowsTesting`

The documentation for the `sideEffects` argument reads:
```
Optional. This can be an expression or one or more filenames or a code chunk surrounded by {...}. This/these will be parsed and evaluated, but nothing returned. This is intended to be used for functions, such as cloud authentication or configurations, that are run for their side effects only. See [setup](http://127.0.0.1:18919/help/library/SpaDES.project/help/setup).
```
This is missing information about the fact that the user can provide a "path" for a fiel hosted on GitHub, that setuProject will download if not available. when adding this information, it will be important to explain that the path is not a URL-like path as in, e.g., "https://raw.githubusercontent.com/PredictiveEcology/Biomass_speciesParameters/main/data/CHECKSUMS.txt",  but rather a path formatted as "<userName>/<repoName>@<branchName>/<folder>/<filename>" or "<userName>/<repoName>/<fileName>" (so "PredictiveEcology/Biomass_speciesParameters@master/data/CHECKSUMS.txt")

I've also noticed that clicking on [setup](http://127.0.0.1:18919/help/library/SpaDES.project/help/setup) takes me to the same help page.

**Comment by eliotmcintire** [comment]
The specification of files is already stated in the **Values and/or files` section**.

**Comment by eliotmcintire** [comment]
Docs modified
