### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.project#6]
Although the templates are currently geared towards workflows for projects using `SpaDES`, I think this package is more general than `SpaDES` _per se_. Since the templated workflows are about implementing a PERFICT workflow (and not SpaDES), perhaps we should rename the package.

Suggestions:
- `perfict`

Thoughts? @eliotmcintire @CeresBarros @tati-micheletti

**Comment by tati-micheletti** [comment]
I like it!!! :)
perfict.projects

**Comment by eliotmcintire** [comment]
I think just `perfict` ... but that may be overselling... After all it
isn't doing all the parts of perfict ... what is it doing?

Depends on what is a) actually in this package and b) whether it is going
to expand its capabilities

If it is

**Comment by achubaty** [comment]
keeping as is for now because it is SpaDES-focussed atm. we can always reassess in the future.

**Comment by CeresBarros** [comment]
I'm not sure if I agree with @eliotmcintire and @tati-micheletti. The structure of the project setup feels quite spades-y (e.g. cache, modules, inputs and outputs folders). Would any king of project benefit from the same structure?
For instance a project could be so simple that it only has one script with a LM that needs small input data files and outputs. Meaning that e.g. the modules/ cache/ folders are not necessary.
 So this project would simply be:

ProjName/
   - inputs/
   - LMscript.R
   - outputs/
   
What I mean is a standard project setup massively depends on the workflows and toolkits used, even if they are all reproducible. It feels strange to me to say "our project setup is ubiquotously useful/applicable for any workflow and toolkit using R" when part of its structure comes from "SpaDES" needs (e.g. a modules/ folder)

**Comment by tati-micheletti** [comment]
Hummm. I think that a more complex structure works for simple projects, even if it feels "bulky" and "spades-y". Even simple projects might want to take advantages of the modular structure and caching, for example (so, modules and caching folders should be there). The other way around, however, is not true. So I think I stand behind the template proposed, even if for simple projects it feels like too much.

**Comment by CeresBarros** [comment]
I see what you mean Tati. I'll have to think a bit more about how someone would try to think about and implement "modules" without it meaning "SpaDES modules", and in a "simpler" way (i.e. without redoing something like a suite of packages and module standards that would be a duplicate of SpaDES) or using another R modelling standard (do we know of a SpaDES equivalent in R?). If this package becomes disassociated from SpaDES it may be good to come up with practical examples of how it's useful within and beyond the SpaDES world.
On 16 Sep 2022, at 23:38, Tati Micheletti ***@***.******@***.***>> wrote:
[CAUTION: Non-UBC Email]

Hummm. I think that a more complex structure works for simple projects, even if it feels "bulky" and "spades-y". Even simple projects might want to take advantages of the modular structure and caching, for example (so, modules and caching folders should be there). The other way around, however, is not true. So I think I stand behind the template proposed, even if for simple projects it feels like too much.

**Comment by tati-micheletti** [comment]
> If this package becomes disassociated from SpaDES it may be good to come up with practical examples of how it's useful within and beyond the SpaDES world.
Yeap. That is a good point. I agree we should brainstorm this.

**Comment by eliotmcintire** [comment]
PERFECT had nothing to do with SpaDES, yet we spoke of reusable modules.
THese are groups of code, *and that are not just scripts*. But, I think a
modules folder would be ubiquitously useful.

packages
modules
cache
inputs
outputs
tmp
